# Generated by Django 3.2.4 on 2021-07-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='Remaining_seats',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
