# Generated by Django 3.2.4 on 2021-07-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210707_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
