# Generated by Django 3.2.4 on 2021-07-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_trip_remaining_seats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.IntegerField(default=-1, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='book',
            name='seatTrain',
            field=models.ManyToManyField(editable=False, to='blog.Seat'),
        ),
        migrations.AddField(
            model_name='trip',
            name='seats',
            field=models.ManyToManyField(editable=False, to='blog.Seat'),
        ),
    ]
