# Generated by Django 3.2.2 on 2021-07-08 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_trip_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stations',
            new_name='Station',
        ),
    ]
