# Generated by Django 3.2.4 on 2021-07-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210711_0701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='seats',
        ),
        migrations.AddField(
            model_name='trip',
            name='seats',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
