# Generated by Django 3.2.2 on 2021-07-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_stations_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='seatNum',
            field=models.IntegerField(default=0),
        ),
    ]
