# Generated by Django 3.2.4 on 2021-07-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_trip_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='seatTrain',
            field=models.ManyToManyField(to='blog.Seat'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='seats',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
