# Generated by Django 3.2.2 on 2021-07-08 19:14

from django.db import migrations
import django_db_constraints.operations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_train_seatnum'),
    ]

    operations = [
        django_db_constraints.operations.AlterConstraints(
            name='trip',
            db_constraints={'destinationValid': 'check (destination >= train.source && destination <= train.destination)', 'sourceIsNotDest': 'check (source != destination)', 'sourceValid': 'check (source >= train.source && source <= train.destination)'},
        ),
    ]
