# Generated by Django 3.2.4 on 2021-07-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210711_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='seatTrain',
            field=models.ManyToManyField(null=True, to='blog.Seat'),
        ),
    ]
