# Generated by Django 3.2.2 on 2021-07-08 19:57

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210708_2153'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trip',
            name='sourceValid',
        ),
        migrations.RemoveConstraint(
            model_name='trip',
            name='destValid',
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(check=models.Q(('source__lte', blog.models.Train.getDest)), name='sourceValid'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(check=models.Q(('destination__lte', blog.models.Train.getDest)), name='destValid'),
        ),
    ]
