# Generated by Django 3.2.2 on 2021-07-08 21:02

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210708_2259'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trip',
            name='sourceValid',
        ),
        migrations.RemoveConstraint(
            model_name='trip',
            name='destValid',
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(check=models.Q(('source__lte', django.db.models.expressions.F('train.destination.id'))), name='sourceValid'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(check=models.Q(('destination__lte', django.db.models.expressions.F('train.destination.id'))), name='destValid'),
        ),
    ]
